/**
 * web-hub session-history plan §4.8 step 3 — HH13/HH14: the continuable-enrollment gates over a
 * REAL filesystem tree shaped like E7's measured sessions tree (250 dirs / 5 616 files, one dir
 * holding 2 625), and the fd-anchored "a dir swapped for a symlink is NEVER followed" gate.
 *
 * Driven against the REAL service (P-scan's own `createHistoryService`, real fds, real cursors)
 * rather than through HTTP on purpose: forcing `enumPartial` needs the plan's parenthetical
 * mechanism — "通过 fs seam 对每次 readdir/lstat 注入 2 ms 延迟亦可" (the 1 ms budget pin it
 * names first races the gen's own root open into `create-failed`) — and that fs seam is
 * service-level; the route's `${principal}:spawn-history` limiter (4 requests / 500 ms refill)
 * would besides turn a ~70-request pagination walk into minutes of 429 back-off. The route
 * layer itself is covered by HH1/HH2 and P-route's committed api tests; what only this suite
 * can prove is the cursor semantics: union(all pages) === all files, zero duplicates,
 * `complete` converges, PD23's per-page mtime ordering, and HH14's SECRET never leaking
 * through a symlinked dir.
 *
 * Regression anchor: these two suites caught a P-scan defect where the page walk never released
 * the per-file "temp" fd reservation (fixed — every header close now releases it exactly once).
 */
import { mkdirSync, mkdtempSync, renameSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { createHistoryService } from "../../src/web-hub/hub/spawn/history/service.js";
import { defaultHistoryFs, type HistoryFs } from "../../src/web-hub/hub/spawn/history/fs.js";
import { createReqDeadline } from "../../src/web-hub/hub/req-deadline.js";
import { decodeHistoryCursor, type HistoryPage } from "../../src/web-hub/protocol/session-history.js";

const IS_LINUX = process.platform === "linux";
const DIRS = 250;
const BIG_DIR_FILES = 2_625;
const TOTAL_FILES = 5_616; // E7's distribution: one dir with 2625, the rest share 2991
/** §4.8 step 3 HH13: per-readdir/lstat delay that pushes a warm-fs enumeration past the real
 * `HISTORY_ENUM_BUDGET_MS` (1.5 s) — 5 616 lstats × 2 ms ≈ 11 s of forced work. */
const STEP_DELAY_MS = 2;

const log = { info(): void {}, warn(): void {}, error(): void {} };
const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

function delayedHistoryFs(): HistoryFs {
  const real = defaultHistoryFs();
  return {
    ...real,
    async readdir(path: string, opts: { withFileTypes: true }) {
      await sleep(STEP_DELAY_MS);
      return real.readdir(path, opts);
    },
    async lstat(path: string) {
      await sleep(STEP_DELAY_MS);
      return real.lstat(path);
    },
  };
}

interface Tree {
  root: string; // <tmp> (acts as HOME)
  agentDir: string;
  dirNames: string[];
  fileCount: Map<string, number>;
}

let tree: Tree | undefined;

function buildTree(): Tree {
  const root = mkdtempSync(join(tmpdir(), "pwh-hist-enum-"));
  const agentDir = join(root, ".pi", "agent");
  const sessions = join(agentDir, "sessions");
  const dirNames: string[] = [];
  const fileCount = new Map<string, number>();
  const remaining = TOTAL_FILES - BIG_DIR_FILES;
  // E7's distribution does not divide evenly: 2 991 over 249 dirs is 12 remainder 3 — the
  // first 3 dirs carry one extra file, so the tree holds EXACTLY TOTAL_FILES (a plain
  // Math.floor under-generated by the remainder — 5 613 — and HH13's union assertion is the
  // exact-count contract, so the fixture must not drift from it).
  const base = Math.floor(remaining / (DIRS - 1));
  const extra = remaining % (DIRS - 1);
  let total = 0;
  for (let d = 0; d < DIRS; d += 1) {
    const name = `d${String(d).padStart(3, "0")}`;
    dirNames.push(name);
    const count = d === 0 ? BIG_DIR_FILES : base + (d <= extra ? 1 : 0);
    fileCount.set(name, count);
    total += count;
    mkdirSync(join(sessions, name), { recursive: true });
    for (let f = 0; f < count; f += 1) {
      writeFileSync(
        join(sessions, name, `s${String(f).padStart(4, "0")}-${d}.jsonl`),
        `${JSON.stringify({ type: "session", version: 3, id: `e${d}x${f}`, cwd: root, timestamp: new Date(1_700_000_000_000 + d * 1_000 + f).toISOString() })}\n`,
      );
    }
  }
  expect(total).toBe(TOTAL_FILES); // fixture guard: the union assertion is an exact count
  return { root, agentDir, dirNames, fileCount };
}

beforeEach(() => {
  tree = buildTree();
});

afterEach(() => {
  if (tree !== undefined && process.env.KEEP_SANDBOX === undefined) {
    rmSync(tree.root, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
  }
  tree = undefined;
});

function svc(agentDir: string): ReturnType<typeof createHistoryService> {
  return createHistoryService(
    {
      agentDir,
      forkSrcDir: join(agentDir, "web-hub", "spawn", "fork-src"),
      registry: { list: () => [] },
      managed: () => [],
      deathOf: () => undefined,
      uid: process.getuid?.() ?? 0,
      hubPid: process.pid,
      now: Date.now,
      log,
    },
    { fs: delayedHistoryFs() },
  );
}

async function walkAll(
  service: ReturnType<typeof createHistoryService>,
  q?: string,
): Promise<{ pages: HistoryPage[]; keys: string[]; requests: number }> {
  const pages: HistoryPage[] = [];
  const keys: string[] = [];
  let cursor: string | undefined = undefined;
  let requests = 0;
  for (;;) {
    requests += 1;
    expect(requests).toBeLessThan(2_000); // walk must terminate
    const res = await service.page(
      { kind: "all", limit: 100, ...(cursor === undefined ? {} : { cursor }), ...(q === undefined ? {} : { q }) },
      createReqDeadline(Date.now, 3_000),
    );
    expect(res.ok).toBe(true);
    if (!res.ok) throw new Error("unreachable");
    pages.push(res.page);
    keys.push(...res.page.items.map((i) => i.key));
    if (res.page.next === undefined) break;
    const next = res.page.next;
    const decoded = decodeHistoryCursor(next);
    expect(decoded).not.toBeNull();
    cursor = decoded!;
  }
  return { pages, keys, requests };
}

describe.skipIf(!IS_LINUX)("web-hub session history — HH13/HH14 continuable enumeration (real fs)", () => {
  it("HH13: enum budget exceeded ⇒ first page incomplete; following `next` covers ALL 5 616 files exactly once, complete converges, per-page mtime descending", async () => {
    const t = tree!;
    const service = svc(t.agentDir);
    try {
      const first = await service.page({ kind: "all", limit: 100 }, createReqDeadline(Date.now, 3_000));
      expect(first.ok).toBe(true);
      if (!first.ok) return;
      expect(first.page.stats.enum.complete).toBe(false); // 2 ms/step ≈ 11 s of work ≫ the 1.5 s budget
      expect(first.page.incomplete).toBe(true);

      const { pages, keys, requests } = await walkAll(service);
      const unique = new Set(keys);
      expect(unique.size).toBe(TOTAL_FILES);
      expect(keys.length).toBe(TOTAL_FILES); // no duplicates across pages (§4.5.3)
      const last = pages[pages.length - 1]!;
      expect(last.stats.enum.complete).toBe(true);
      expect(last.next).toBeUndefined();
      expect(last.incomplete).toBeUndefined(); // nothing was skipped/changed
      // PD23: every page's own items are mtime-descending (ties broken by key ascending)
      for (const page of pages) {
        for (let i = 1; i < page.items.length; i += 1) {
          const a = page.items[i - 1]!;
          const b = page.items[i]!;
          expect(a.mtimeMs).toBeGreaterThanOrEqual(b.mtimeMs);
        }
      }
      // E7-shaped bound: enum rounds (≤ one advance per dir) + walk pages + slack
      expect(requests).toBeLessThan(DIRS + Math.ceil(TOTAL_FILES / 100) + 200);
    } finally {
      await service.dispose();
    }
  }, 240_000);

  it("HH14: a not-yet-enumerated dir swapped for a symlink is never followed — SECRET-TITLE never appears, changed===1, incomplete stays true, q finds nothing", async () => {
    const t = tree!;
    const service = svc(t.agentDir);
    try {
      const first = await service.page({ kind: "all", limit: 100 }, createReqDeadline(Date.now, 3_000));
      expect(first.ok).toBe(true);
      if (!first.ok) return;
      expect(first.page.stats.enum.complete).toBe(false);
      const seen = new Set(first.page.items.map((i) => i.key));

      // pick a dir the enumeration has NOT reached yet (its files must not have surfaced)
      const victim = t.dirNames.find((d) => ![...seen].some((k) => k.startsWith(`${d}/`)));
      expect(victim).toBeDefined();
      const victimDir = join(t.agentDir, "sessions", victim!);

      // the decoy behind the symlink: a perfectly valid session file whose title is SECRET
      const outside = join(t.root, "outside");
      mkdirSync(outside, { recursive: true });
      writeFileSync(
        join(outside, "secret.jsonl"),
        `${JSON.stringify({ type: "session", version: 3, id: "secret0", cwd: t.root, timestamp: new Date().toISOString() })}\n${JSON.stringify({ type: "message", id: "sm", timestamp: Date.now(), message: { role: "user", content: [{ type: "text", text: "SECRET-TITLE" }] } })}\n`,
      );
      renameSync(victimDir, `${victimDir}.hidden`);
      symlinkSync(outside, victimDir);

      const { pages, keys } = await walkAll(service);
      expect(keys.some((k) => k.includes("secret"))).toBe(false);
      for (const page of pages) {
        expect(JSON.stringify(page.items)).not.toContain("SECRET-TITLE");
      }
      const last = pages[pages.length - 1]!;
      expect(last.stats.changed).toBe(1); // the swapped dir, consumed deterministically
      expect(last.incomplete).toBe(true);

      // a fresh query through the same fd-anchored rules still cannot see it
      const again = await service.page({ kind: "all", limit: 100, q: "SECRET" }, createReqDeadline(Date.now, 3_000));
      expect(again.ok).toBe(true);
      if (again.ok) expect(again.page.items).toHaveLength(0);
      // the real dir's own files are ALSO gone from the listing (renamed away) — nothing followed
      expect(keys.some((k) => k.startsWith(`${victim}/`))).toBe(false);
    } finally {
      await service.dispose();
    }
  }, 240_000);
});
